export const CUSTOM_OPTION = '__custom__';

export const DEPARTMENTS = [
  'Accounting and Finance',
  'Agricultural Economics',
  'Agricultural Engineering',
  'Animal Science',
  'Biology',
  'Chemistry',
  'Civil Engineering',
  'Computer Science',
  'Construction Technology and Management',
  'Economics',
  'Education',
  'Educational Planning and Management',
  'English Language and Literature',
  'Geography and Environmental Studies',
  'Geology',
  'History and Heritage Management',
  'Human Resources',
  'Information Technology',
  'Law',
  'Management',
  'Mathematics',
  'Mechanical Engineering',
  'Nursing',
  'Physics',
  'Plant Science',
  'Psychology',
  'Public Health',
  'Registrar',
  'Research and Community Service',
  'Sociology and Social Anthropology',
  'Student Affairs',
  'Veterinary Medicine',
];

export const POSITION_OPTIONS = [
  'Lecturer',
  'Assistant Lecturer',
  'Associate Professor',
  'Assistant Professor',
  'Professor',
  'Graduate Assistant',
  'Teaching Assistant',
  'Department Head',
  'Dean',
  'President',
  'Vice President',
  'Registrar',
  'Director',
  'Researcher',
  'Laboratory Technician',
  'Librarian',
  'ICT Officer',
  'Accountant',
  'Human Resources Officer',
  'Administrative Assistant',
  'Student Affairs Officer',
  'Procurement Officer',
  'Nurse',
  'Doctor',
  'Engineer',
  'Security Officer',
  'Driver',
  'Cleaner',
];